### ISSUE TITLE
Entity_assembly_id would be useful while fetching chemical shift data

### ISSUE THREAD

**Issue by kumar-physics** [uwbmrb/BMRB-API#58]
The combination of (entry_id.entity_id,seq_id,cs_list_id ) is not unique for some entries(example : homo dimer or multiple conformers (entry 6743)). When I try to construct unique list by fetching all  nitrogen chemical shifts(http://dev-api.bmrb.io/v2/search/chemical_shifts?comp_id=ALA&atom_id=N) , I found some duplicate records

['6743', 1, 56, 'ALA', 'N', 'N', 125.63, 0.1, 1, 1, 7.5, 298]
['6743', 1, 56, 'ALA', 'N', 'N', 126.68, 0.1, 1, 1, 7.5, 298]

It is not actually duplicate, but missing Entity_assembly_id (or chain id). Adding Entity_assembly_id would be useful for some statistical analysis.

**Comment by dmaziuk** [comment]
entity_assembly_id is part of the key. In fact it should be used **instead** of entity_id precisely because of homodimers etc. You could join entity_assembly table on it and pull asym_id and/or chain_id from there for the query. 

If the entry is missing it, the entry should be fixed. For an entry that old, a 2.1 file may provide the clue as to which chain is which. (I can't get to www.bmrb.io and check the entry, not sure if it's temporary or UConn's blocking all of Ukraine.) This may be  a 2.1->3.1 conversion problem.

**Comment by kumar-physics** [comment]
Entity_assembly_ID exists in the entry, but it's not part of API return. I think BMRB website is down from yesterday. I am also not able to reach.

**Comment by jonwedell** [comment]
Implemented.
